version: '3'
services:
  common:
    image: grpc-common
    build:
      context: ./
      dockerfile: ./docker-common/grpc.Dockerfile

  gateway:
    image: grpc-gateway
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
    ports:
      - "5000:5000"
      - "9091:9091"
    links:
      - grpc_node_service

  grpc_node_service:
    image: grpc_node_service
    build:
      context: ./
      dockerfile: ./node-service/Dockerfile
    depends_on:
      - common
    ports:
      
      - "9000:9000"
      
  webapp:
    build:
      context: ./
      dockerfile: ./web-app/Dockerfile
    depends_on:
      - common
    image: grpc-webapp
    ports:
      - "3000:3000"